Alter TABLE Meta ADD COLUMN IF NOT EXISTS show_teacher BOOLEAN DEFAULT TRUE;
Alter TABLE Meta ADD COLUMN IF NOT EXISTS show_subject BOOLEAN DEFAULT TRUE;
Alter TABLE Meta ADD COLUMN IF NOT EXISTS show_room BOOLEAN DEFAULT TRUE;